### ISSUE TITLE
How does bambi decide how many chains to use?

### ISSUE THREAD

**Issue by amelio-vazquez-reina** [bambinos/bambi#100]
How does bambi decide how many chains to use? Separately, I run into this warning today, I'm not sure I understand what it really means. Is it safe to ignore it?

``` python
names = results.summary()
/Users/amelio/anaconda3/envs/py36/lib/python3.6/site-packages/bambi/results.py:346: UserWarning: Multiple MCMC chains are required in order to compute 
convergence diagnostics.                                                                                                                              
  warnings.warn('Multiple MCMC chains are required in order '
```

**Comment by jake-westfall** [comment]
It's safe to ignore. By default, bambi samples with a single MCMC chain. There's nothing wrong with this, however, if you use multiple chains then the `summary()` method returns two additional columns of convergence diagnostic statistics, which can be useful. These statistics require multiple chains because they depend on computing the between-chain variance in the samples.

**Comment by tyarkoni** [comment]
If you're asking how to specify the number of chains, @amelio-vazquez-reina, you can specify it explicitly:

```python
model.fit(..., chains=4)
```
Closing this, but feel free to re-open if needed.
