### ISSUE TITLE
No easy way to override default prior args for Y?

### ISSUE THREAD

**Issue by jake-westfall** [bambinos/bambi#16]
It looks like there's no easy mechanism for overriding the default prior args for the outcome Y. One can easily change the *family* through the `family` parameter of `add_y()`, but if one wanted to use, say, a Normal family with the prior SD set to something other than the default, right now it looks like the only mechanism for doing so is by passing an argument to `default_priors` while initializing the model. It would be easier and more intuitive if one could do this in the call to `set_y()`. So maybe we want to do something like give `set_y()` an optional `prior` parameter that would override the default.

**Comment by tyarkoni** [comment]
I added an explicit `prior` argument in `add_y`.

I didn't modify `set_y` at all, but I'm leaning towards removing it entirely; I think it's a bit confusing to have both `add_y` and `set_y`. It seems reasonable to expect users to know in advance of model specification which variable is going to be the outcome, and since the overhead of setting up a model is now much lower than before (since nothing gets compiled until `build()` or `fit()` are called), I don't know that there's a need for a `set_y` call anyway. Any objections?

**Comment by jake-westfall** [comment]
I agree about it being confusing to have both `add_y` and `set_y`, I had the same thought while going through the code.
