### ISSUE TITLE
Default Priors Bernoulli Family with Perfect Separation

### ISSUE THREAD

**Issue by jlevy44** [bambinos/bambi#320]
Hi there! Thanks for this awesome package! I see you're using the MLE estimate to help determine the scaling of the priors. This may fail in the case where there is perfect separation in a logistic regression model, which I had seen on an initial test. If prior is set to none, maybe is it possible to toggle some of the prior rules / default priors from https://mc-stan.org/rstanarm/ or brms, etc. when this happens? 

Thanks!

https://github.com/bambinos/bambi/blob/8f1679810f7cd132ebdd47a1b64ac82e197b63df/bambi/priors.py#L215

**Comment by tomicapretto** [comment]
Hi @jlevy44, thanks for opening this issue! 

This is something we are aware of, and we are starting to do some research on default priors with the aim to improve what is currently being done in Bambi. #278 is also another consequence of our default prior system. 

We've been in touch with some brms/rstanarm devs and they also want to improve their current default priors. So, at least for now, the goal is to do more research on the subject and implement something that improves over Bambi/brms/rstanarm defaults, instead of porting brms/rstanarm priors to Bambi.

If you still want to use rstanarm default priors, [this guide](https://mc-stan.org/rstanarm/articles/priors.html) will be helpful. As far as I've seen in some empirical comparisons between our default priors and rstanarm default priors, you won't see any significant difference between the posteriors _in general_. 

I'm leaving this issue open and will post any update to our default prior system here. Again, thanks for writing!

**Comment by jlevy44** [comment]
Thanks for your response. I am aware of the default priors offered by rstanarm and may try them out using this package. I agree, I think it's great that your group is researching ideal default priors. I usually set my own based on the use case, excited to see what you come up with!

**Comment by tomicapretto** [comment]
Development version now uses priors inspired on rstanarm priors, which should overcome this perfect separation problem with older default priors.
