### ISSUE TITLE
Replacement for pymc3.glm?

### ISSUE THREAD

**Issue by twiecki** [bambinos/bambi#38]
This looks really cool.

It seems like this by far supersedes the pymc3.glm functionality. That maybe should have been a separate package from the beginning. Do you think that's accurate? In that case, I wonder if I should get rid of `pymc3.glm` and instead refer to this package. Any thoughts?

**Comment by tyarkoni** [comment]
Thanks! I was planning to open an issue on the PyMC3 repo next week to discuss this, but that was pre-empted by the tweets today. :)

Initially I thought this could be a drop-in replacement for the glm module, but one thing it currently does that's kind of nice is completely separate abstract term specification from model estimation. Even though PyMC3 is currently the only back-end implemented in Bambi, the long-term ideal would be to add back-ends for, e.g., Stan, statsmodels, etc., which would allow users to easily fit the same model using different packages (and compare them). So I think it makes sense to keep this a separate package, even though at the moment there's nothing it does that isn't reliant on PyMC3.

That said, I don't know that the `pymc3.glm` module needs to be removed, since it's perfectly functional. You could keep it in as-is, but maybe just direct users who want greater functionality to Bambi. Alternatively, it'd be fine with me if you want to integrate a stripped-down version of Bambi (that mainly loses the separation between abstract model and computational back-end) into PyMC3. The only real downside I see with the latter approach is that maintenance might become more difficult.

**Comment by twiecki** [comment]
Yeah, I definitely agree that this should stay it's own package. Probably glm can also stay where it is. Closing.

Another question, is it possible at all to interact with the model at the PyMC3 level (similar go pymc3.glm)?

**Comment by tyarkoni** [comment]
The PyMC3 model is always available in `model.backend.model`, so in that sense, yes--you can always grab it at any time and modify it further before you `run` the model in Bambi (and retrieve it after the fact). But we could perhaps make it easier to work with? Let me know if you have suggestions.
