### ISSUE TITLE
Summary output for two-level categorical variables

### ISSUE THREAD

**Issue by palday** [bambinos/bambi#41]
The model summary / coefficients for two-level categorical variables (whether a `str` or `Categorical` in `pandas`) in displays the term name but not the level / contrast generated by `patsy`. This makes interpreting the output somewhat more difficult.

Inspecting the model structure a bit, I see that `model.terms['binary_var'].categorical == False`. Binary variables do have an obvious treatment coding, but I always have trouble determining/remembering the reference level in `patsy`. (According to the documentation it's the 'first' level, but does that mean the first level to appear in the data frame? That can change. In R, 'first' is determined based on lexicographic ordering.)  

I haven't yet tinkered with a many leveled variable to see what happens there.

**Comment by jake-westfall** [comment]
I'm actually working on this as we speak!

For factors with >2 levels, the ModelResults.plot() method should nicely annotate the traceplot with the corresponding factor levels. I'm almost done modifying ModelResults.summary() so that it will return a pandas DataFrame with factor levels nicely labeled for all applicable terms.

**Comment by palday** [comment]
Awesome.
