### ISSUE TITLE
Is it possible to do an online update of the posterior?

### ISSUE THREAD

**Issue by afg1** [bambinos/bambi#421]
Hello,

I'm not 100% sure how to phrase this question, so let me know if anything is unclear.

I would like to be able to do a kind of online learning approach with bambi where I update my posterior with new data after fitting, My use case for this is that I have a huge multi-level model which doesn't fit in memory if I try to fit on the whole dataset, so my idea was to effectively fit in batches.

I have a feeling this will be deceptively simple, but I don't see anything about how to do it in the documentation. Is this something I can do?

Thanks!
Andrew

**Comment by aloctavodia** [comment]
I am not aware of a simple way to achieve this with PyMC or other similar PPLs. In order to be able to do this, we should turn the posterior into a new prior, but given that the posterior is approximated as samples and priors are specified using mathematical expressions we need a good way to turn samples into those mathematical expressions. And while possible (at least approximately) is not straightforward to do with PyMC or other PPLs. Another solution could be to used a modified version of SMC, but again that modified version is not implemented in PyMC. Maybe you can ask in https://discourse.pymc.io/ in case someone else has another idea.
