### ISSUE TITLE
Support for log-transforms (and other arithmetic) in formula?

### ISSUE THREAD

**Issue by martiningram** [bambinos/bambi#455]
Hi all,

I'm a big fan of bambi, thanks for all your great work!

I have a question about more complicated formulas. I'm currently trying to fit models taken from a [textbook](http://www.stat.columbia.edu/~gelman/arm/). One of the formula strings used there is:

```
log(weight) ~ log(I(diam1 * diam2 * canopy_height)) + log(I(diam1 * diam2)) + log(I(diam1 / diam2)) + log(total_height) + group
```

In other words, it includes log transformations, and also some other arithmetic operations. What I'm curious about is whether bambi supports this in some way, or whether all such transformations should be done beforehand, e.g. by creating a variable `log_total_height = np.log(total_height)`?

Thanks for your help!

**Comment by tomicapretto** [comment]
Hi @martiningram

Bambi has support for those. 

* You can pass Python functions as your model terms. 
* You can wrap mathematical operations between terms within `I()` or using the shorthand `{}`.

For example, the formula you're sharing would be

```python
import numpy as np
formula = "np.log(weight) ~ np.log(diam1 * diam2 * canopy_height) + np.log(diam1 * diam2) + log(diam1 / diam2) + np.log(total_height) + group"
```

Note that I'm not using `I()` because the operations are carried within the arguments of a function, so they are interpreted as regular Python code, and not as model formula code. 

If you want a term that is the result of doing some math operation between variables, you do need `I()` or `{}.

For example

```python
formula = "y ~ I(x * z)"
formula = "y ~ I(x / z)" # 1
formula = "y ~ {x / z}"  # 2
formula = "y ~ {10 * x}"
```

\\#1 and \\#2 are equivalent

**Comment by martiningram** [comment]
Wow, this is working a treat, thanks Tomas! I was even able to use the formula as-is by defining

```python
def log(x):
    return np.log(x)
```

Am I right in assuming that keeping the `I` is OK, even though it's actually not required as you say?

**Comment by tomicapretto** [comment]
@martiningram that's right. `I()` is literally an identity function. It returns whatever you pass in.

**Comment by martiningram** [comment]
Terrific, thanks Tomas! This is working very well, so I am closing this issue!
