### ISSUE TITLE
Allow priors on fixed effects to be given on standardized scale

### ISSUE THREAD

**Issue by jake-westfall** [bambinos/bambi#6]
Two candidates for alternative ways to set priors on the fixed regression coefficients:

- Normal or Cauchy priors on the standardized regression coefficients
- Beta priors (scaled/shifted to be in [-1,1] range) on the partial correlation coefficients

Priors on the partial correlations would be a little nicer, but both would be viable solutions to the scaling problem (i.e., the same prior on a raw regression coefficient would be more or less informative depending on the scales of X and Y). Setting priors on the partial correlations could perhaps even be the default, unless the user elects to put priors directly on the regression coefficients.

**Comment by jake-westfall** [comment]
Smart default priors are now implemented! They work pretty much exactly as I wrote above (but slightly different). However, it is still not possible for users to specify their own priors on this partial correlation scale. So we should still add that.

**Comment by tyarkoni** [comment]
I think the easiest and most user-friendly thing to do here is to just allow the `prior` argument (anywhere it's currently accepted) to be set to an int or float. Then we can check type, and if a numeric value is passed, we assume the user intends to use default priors with the specified sd or whatever. Otherwise we fall back on the current approach.

**Comment by tyarkoni** [comment]
Take a look at #8dc9473fbf5781d. I refactored the scaling code so that all of the work is now done in a new `PriorScaler` class in priors.py.  I also renamed `.default_prior_info` to `.dm_statistics`, but feel free to change if you prefer the former. That data is now saved in the `Model` instance so that the `PriorScaler` can easily retrieve it.

The other thing I added was support for named widths (stored in `PriorScaler.names`). I added all of the ones you suggested in your comments ('wide', 'ultrawide', 'medium', and 'narrow'). This means a user can now do things like:

```
# Set single term prior
model.add_term('X1', prior='narrow')

# ...or use the new set_priors() method to do fancier stuff
model.set_priors({'X1': 0.42, 'X2': 'medium'}, fixed='narrow', random='ultrawide')
```

The existing tests run fine, but since they're not actually testing whether the scaling is working properly, that's not really diagnostic of much. Please take a look, and maybe add a few tests to test_priors.py.

**Comment by jake-westfall** [comment]
I get errors when building any model with random effects. Before trying to fix this I'll write a few tests that catch the errors (and some others that should work currently, but would be good to test anyway). The new tests will only get run if I merge them in as a new branch, right? So I should do it that way? Or is there a way to just do a normal push and then make it run the tests.

**Comment by tyarkoni** [comment]
Tests will run on any branch you push to GitHub, no need to merge. But you can also just run them locally if it helps to get them working.

While you're doing that I'll try to debug. The test model currently in tests doesn't include any random effects, so I'm not terribly surprised it's failing.

**Comment by tyarkoni** [comment]
Should be fixed now if you pull from master.
