### ISSUE TITLE
Explore alternative parameterization of random effects

### ISSUE THREAD

**Issue by jake-westfall** [bambinos/bambi#62]
Inspired by an interesting and (I think) important [blog post](http://twiecki.github.io/blog/2017/02/08/bayesian-hierchical-non-centered/) by @twiecki. We have definitely seen this sampler behavior in several of our models.

A big implication could be that our current (traditional) parameterization of random effects may tend to overestimate the variances of random effects whose true variances are near 0. This would be particularly important for random stimulus effects, which in very many cases are less variable than random subject effects (in fact, random stimulus slopes very often have near-0 variance). This is further exacerbated by the unfortunate fact that much of psychology/neuroscience tends to use quite small stimulus samples, so that even relatively small overestimates in the stimulus variance can result in a non-trivial decrease in the precision of posteriors for the effects of interest.

It is also possible that this alternative parameterization could result in faster sampling, since presumably fewer proposals would be rejected while the sampler is exploring the low-random-effect-variance part of the parameter space... I think.

Anyway, we should do some experimentation and systematic comparison between parameterizations.

**Comment by paul-buerkner** [comment]
The non-centered version will almost certainly be much better both with respect to convergence and sampling speed. At least it is much better than the naive implementation when fitted in Stan. Thus, I highly recommend adopting this parameterization.

**Comment by jake-westfall** [comment]
Thanks for chiming in on this, Paul. I don't suppose you have documented examples of the alternative parameterization working better for some realistic datasets in Stan?

**Comment by paul-buerkner** [comment]
I have run quite a few comparisions when implementing this in brms (which solely uses the non-centered version), but I can't find the code right now.

For single group-level effects, the difference might be somewhat subtle (but still relevant; see twiecki's example). When having multiple correlated group-level effects, however, the difference will be huge:

Naive, we have (in pseudo code):
```
u ~ multi_normal(mu, Sigma)
```
where `mu` is the mean vector and `Sigma` is the covariance matrix. When using the non-centered version, we have
```
z ~ normal(0, 1)
u = mu + diag(sigma) * L_Omega * z
```
where `sigma` is the vector of standard deviations and `L_Omega` is the cholesky factor of the correlation matrix. You can almost "see" that the non-centered version is easier for the sampler.

The rethinking R package (https://github.com/rmcelreath/rethinking), which also uses Stan on the backend, actually has both implementations so that is should be easy for you doing some simulations with it.
