### ISSUE TITLE
Formulae Question for different intercept per group

### ISSUE THREAD

**Issue by canyon289** [bambinos/bambi#648]
When I want different intercepts per category I do this  `"Goals ~ Days_Since_First_Game:Team + Team + 0"` (I believe)

If my understanding above is correct why isn't supported `Goals ~ Days_Since_First_Game:Team + 1:Team`? This seems like a more natural way to represent group specific intercepts, but I feel perhaps I'm missing something.

Data and mode for context
![image](https://user-images.githubusercontent.com/7213793/222875799-a8fd91b9-ddef-45b2-bd09-1cf02b2a51ee.png)

**Comment by tomicapretto** [comment]
Because `1`, `0` and `-1` are very special terms in the model formula that are used to represent the presence or absence of an intercept in the model. But in general, numbers don't make sense as terms in a model formula.

`Days_Since_First_Game:Team` works because it is the interaction between two terms. On the other hand, `1:Team` is the interaction between a number and a model term. And numbers don't make sense in this context.

**Comment by canyon289** [comment]
Got it makes sense. Thanks Tomas!
