### ISSUE TITLE
'backend' as a parameter of Model.build, not Model.__init__

### ISSUE THREAD

**Issue by jake-westfall** [bambinos/bambi#70]
Basically right now if we want to compare results between pymc3 and stan for the same model and data, we do something like:

    pymc3_model = Model(data, backend='pymc3')
    pymc3_fitted = pymc3_model.fit('y ~ x')
    stan_model = Model(data, backend='stan')
    stan_fitted = stan_model.fit('y ~ x')

I think something like this would be neater:

    model = Model(data)
    pymc3_fitted = model.fit('y ~ x', backend='pymc3')
    stan_fitted = model.fit(backend='stan')

Where the argument to 'backend' here gets passed through fit() to build(). I think this would make more sense because then the model specification is totally abstracted away from the sampling method. (Well, in the second example I specified the model and the pymc3 backend in the same call, so that the abstraction is not as obvious, but to be even more clean we could first specify the model using add_formula() followed by two separate calls to fit().)

**Comment by tyarkoni** [comment]
Makes sense. The only issue I can see is that right now there can only be one `.backend` object in `Model`. I think a reasonable (minor API-breaking) solution is to make `.backend` either a list or dict, so that the user can then pass in multiple backends a initialization and/or model-fitting. That would actually allow us to reduce the code further to this:

```python
model = Model(data)
pymc3_fitted, stan_fitted = model.fit('y ~ x', backend=['pymc3', 'stan'])
```

By default, `.fit()` would use the first available backend, but if a list is passed, it would return a list of results.

**Comment by jake-westfall** [comment]
I like that.
