### ISSUE TITLE
Example notebook -- `r2_y` not in dm_statistics

### ISSUE THREAD

**Issue by arokem** [bambinos/bambi#78]
Hi! Running the example notebooks, I encountered the following error:

![screen shot 2017-03-15 at 9 06 10 pm](https://cloud.githubusercontent.com/assets/118582/23981450/f3486c6a-09c3-11e7-9630-87a8f69de602.png)

It looks like maybe `model.dm_statistics` does not have the `r2_y` statistic?

I believe I am working off of current `master`.

**Comment by arokem** [comment]
While I'm here -- a question: is there a particular reason that the other notebook has a `%qtconsole` magic incantation in the first cell?

**Comment by jake-westfall** [comment]
Ah yes, the notebook needs to be updated :)
`r2_y` is (was) a vector of *k* R^2 coefficients from regressions where, for each of the *k* fixed-effect predictors, we regress the outcome on the *k*-1 *other* predictors. This used to be stored in the Model object because it was used for some other computations internally as well, but we no longer perform those other computations, and thus `r2_y` is no longer computed or stored. So this now needs to be computed manually.

As for `%qtconsole`, it's just because I wrote the notebook and I like to also have a qtconsole attached to the notebook kernel handy while I'm working. I probably meant to remove that cell before posting.
