### ISSUE TITLE
Add convenient function to access list of inference methods

### ISSUE THREAD

**Issue by tomicapretto** [bambinos/bambi#791]
In #775 we got access to a great variety of samplers through bayeux. Now I realize it's not that easy to get a list of inference methods. The docstring mentions `model.backend.inference_methods['bayeux']` but that means we not only need a Bambi model, but a Bambi model that has already been built.

I think we should have a convenient function to get that list in an easier way. I imagine something like:

```python
import bambi as bmb

bmb.get_inference_methods()
```

that uses the existing logic to return the appropriate list of inference methods, depending on whether bayeux is installed or not.

**Comment by GStechschulte** [comment]
The reason we need a defined and built Bambi model is because with `bayeux` algorithms are dynamically determined at [runtime](https://jax-ml.github.io/bayeux/inspecting/).

I do think it should be simpler to a list of inference methods. I can imagine defining a "dummy model" similar to [here](https://github.com/bambinos/bambi/blob/714ccb7b0c0fcd9e2d66f60ccdafb792c600f70c/bambi/backend/pymc.py#L452) to return a list of methods without the user needing to define and build a model. 

Another area of improvement I see is how the user can obtain the set of kwargs for a particular inference method.  Currently this requires calling `bayeux` directly, e.g.

```python3
bx.Model.from_pymc(model.backend.model).mcmc.blackjax_nuts.get_kwargs()
```

Since different samplers have different kwargs, it should be easier for the user to know what these are.

**Comment by tomicapretto** [comment]
I agree the dummy model is the way to go. So what we need is a function similar to the one you linked, that also includes the alternatives built-in pymc, right?

**Comment by GStechschulte** [comment]
Yup, I believe so. I can work on it this week 😄

**Comment by GStechschulte** [comment]
We also need to restrict what is returned when calling `get_inference_methods`. Currently, `model.backend.inference_methods` returns all bayeux methods. However, Bambi does not implement bayeux optimize algorithms for example. 

Nonetheless, if the user attempts to pass `jaxopt_bfgs` to fit the model, the following error will be raised

```
NotImplementedError: 'jaxopt_bfgs' method has not been implemented
``` 

We should be more consistent to not confuse the users.
