### ISSUE TITLE
Enable Poisson models with different observation times

### ISSUE THREAD

**Issue by ivlis** [bambinos/bambi#841]
I am trying to adapt my raw pymc model into bambi framework. In my model the data captures the number events within a certain time. For each observation the time is different. In pymc I'm using the following likelihood:

```
like = pm.Poisson("like", mu = rate*observation_time, observed = events, ...)
```

I struggle to convert this to `bambi`, I would like to have something like 

```
r[events, observation_time] ~ 1
```

similarly to `p[A,B]` for Binomial.

**Comment by GStechschulte** [comment]
Hey @ivlis thanks for the question. To account for the varying observation times, it might be possible to use `offset` within the Bambi model.

```python3
model = bmb.Model('events ~ predictors + offset(time)', 
                  data=df, 
                  family='poisson')
```

If I understand correctly, the `offset` term can be used when you have count data where the exposure time or rate varies across observations. It allows you to model the rate of events rather than just the raw counts. @tomicapretto am I wrong here?

[Here](https://gist.github.com/aflaxman/838fece08770d68e1410320e27289f16) is a Gist with an example implementation.

**Comment by ivlis** [comment]
Yeah, perfect this should work becase of log link function. Thank you.
