### ISSUE TITLE
results.get_trace() deprecated?

### ISSUE THREAD

**Issue by amelio-vazquez-reina** [bambinos/bambi#89]
Up until two weeks ago, I was able to do:
``` python
model   = Model(test)
results = model.fit('y ~ treatment',  samples=5000)
```

And then:
``` python
samples = results.get_trace()['treatment']
```

with the new release, what is the equivalent command? I get an error for `get_trace()`

``` python
results.get_trace()
#---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-14-6ebe91e66336> in <module>()
----> 1 results.get_trace()

AttributeError: 'MCMCResults' object has no attribute 'get_trace'
```

Should I perhaps use the following instead?
``` python
samples = model.backend.trace.get_values('treatment')
````

Or does that return something else?

**Comment by tyarkoni** [comment]
Assuming you're using the (default) PyMC3 backend, you can find the PyMC3 trace in `model.backend.trace`. There is no longer any `get_trace()` method because we now have multiple backends, and for the Stan backend, there isn't an equivalent stand-alone class like pymc's `MultiTrace`.

Note that if you want to manipulate the sample data yourself (rather than relying on PyMC3's built-in functionality), you can play around with the `MCMCResults` object itself, as it contains all of the individual samples too. Indexing is very similar to the `MultiTrace`, but probably actually a bit more flexible. But we don't support nearly as many plotting/summarizing/evaluation functions as PyMC3 at the moment.

**Comment by tyarkoni** [comment]
Oh, sorry: and to answer your question re: your example, you should be able to just do something like:

```python
model   = Model(test)
results = model.fit('y ~ treatment',  samples=5000)
treatment_samples = results['treatment']
```

So it's actually much easier than before.

**Comment by amelio-vazquez-reina** [comment]
Great. Thanks @tyarkoni!

One more question. The original `results.plot()` method still works, right? If so, how is it different from this?
``` python
import pymc3 as pm
pmtrace = model.backend.trace
pm.traceplot(pm_trace)
```
Also, I guess `results.plot()` doesn't render the red vertical lines for E[x] anymore right?

**Comment by tyarkoni** [comment]
Yes, `results.plot()` will still work. And it differs from the pymc3 plot to exactly the degree that you can see visual differences. :)

In terms of implementation, we no longer call pymc3's plotting directly (though we still use some of its helpers). This is so we can apply the same plot to results that come out of the Stan backend.

We'll add the vertical lines back in at some point as time allows; they were an incidental casualty of major refactoring, and it wasn't a principled decision to leave them out.

**Comment by amelio-vazquez-reina** [comment]
Phenomenal. Thanks @tyarkoni.
