### ISSUE TITLE
Deprecation warnings with Pandas with pandas.core.datetools

### ISSUE THREAD

**Issue by amelio-vazquez-reina** [bambinos/bambi#97]
Not sure where exactly the problem will be, but I started getting the following warning after upgrading Pandas to the latest version (0.20.1):

``` python
> from bambi import Model
/Users/amelio/anaconda3/envs/py36/lib/python3.6/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.                                                          
  from pandas.core import datetools

> import pandas as pd
pd.__version__
'0.20.1'

```

**Comment by tyarkoni** [comment]
Closing this, as it appears to be a statsmodels issue and not a bambi issue.

**Comment by amelio-vazquez-reina** [comment]
Thanks @tyarkoni do you know if there is an issue in statsmodels addressing this? [This](https://github.com/statsmodels/statsmodels/issues/3332#issuecomment-268291991) is the only issue I found (and a related post from @josef-pkt the statsmodels mailing list). Also, for what is worth, I can `import statsmodels` without getting the warning.

**Comment by josef-pkt** [comment]
@amelio-vazquez-reina  about statsmodels: 
numpy and pandas have faster release cycles and statsmodels often lags in catching up with deprecations and deprecation warnings. However, they are usually fixed after a short delay. Deprecation warnings in statsmodels can be ignored by users. (reporting deprecation warnings in statsmodels master is still useful in case we are slow in seeing them).  
AFAIR, that specific deprecation has been fixed in statsmodels master

**Comment by amelio-vazquez-reina** [comment]
Thanks @josef-pkt Makes sense. 👍
